defaults: &defaults
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: 127.0.0.1
  username: root
  password: 

development: &DEV
  <<: *defaults
  database: stirchleystores_development

test: &TEST
  <<: *defaults
  database: stirchleystores_test

production:
  <<: *defaults
  database: stirchleystores_production